### ISSUE TITLE
Recipe encoding not detecting small crafts correctly 

### ISSUE THREAD

**Issue by rythin-sr** [MartinSVK12/retrostorage#11]
If a recipe is smaller than the full 3x3 grid, for example sticks, the recipe needs to be put in the top left of the grid for the encoding to work, otherwise the recipe disc will encode "null".

**Comment by MartinSVK12** [comment]
Don't really know how to fix this and it isn't that serious so won't fix for now.
Might reopen this if I find a solution in the future.
