### ISSUE TITLE
Autocrafted storage discs "sync up" even across worlds

### ISSUE THREAD

**Issue by rythin-sr** [MartinSVK12/retrostorage#13]
Inserting an item into an autocrafted storage disc will add it to every other existing and future autocrafted discs. It appears that taking out items from any disc doesn't change this behaviour, all disc retain what has been put into them.

These items sync up across worlds, but get reset after closing and re-opening the game. A similar effect can be achieved by giving yourself the discs through HMI.

Repro steps:
-give yourself 2 or more discs through hmi, or have a retrostorage system craft them for you
-insert one disc into a digital chest, then put an item in the disc
-all discs should now have this item inside them

https://user-images.githubusercontent.com/49848633/173843245-0d12bc2c-52fb-4585-8d2f-f996003ac3a0.mp4

**Comment by MartinSVK12** [comment]
Fixed.
