### ISSUE TITLE
Autocrafting uses items from all stacks beyond the first 64

### ISSUE THREAD

**Issue by rythin-sr** [MartinSVK12/retrostorage#14]
Having one stack of 64 of a crafting ingredient, and then multiple others will use the required ingredients for a craft from all stacks except the first one, unless the craft would use all remaining ingredients, then it will use some from the 64-stack aswell.

https://user-images.githubusercontent.com/49848633/173844986-d6d8c659-c3a7-4d51-8414-89702cdd6a54.mp4

**Comment by MartinSVK12** [comment]
Fixed.
