### ISSUE TITLE
Failed autocrafting request affecting future successful requests

### ISSUE THREAD

**Issue by rythin-sr** [MartinSVK12/retrostorage#16]
Attempting to request an autocraft while not having enough ingredients makes the next successful autocraft happen 3 times. Attempting to craft the item you're lacking ingredients for again after that crafts a fourth of the previous item. Doesn't happen if the UI is left between the unsuccessful craft and the successful one.

Repro steps:
-set up 2 recipe discs with recipes requiring different materials, a chest and a furnace for example
-insert wood into the system
-request a furnace to be crafted, then, without leaving the UI, request a chest
-there should be 3 chests waiting for you in the output slot
-attempting to request a furnace again will make another chest, but only the first time, further clicks do nothing

Items consumed by the crafting appear to be the correct amounts, except for #14

**Comment by MartinSVK12** [comment]
Fixed.
