### ISSUE TITLE
Buildcraft pipe issues

### ISSUE THREAD

**Issue by rythin-sr** [MartinSVK12/retrostorage#2]
Buildcraft pipes can connect to digital and request terminals. Piping items into them will put the items in the output slot, if the item being pumped in isn't already stored in the system. If it is stored in the system, the items will be voided instead. (the item in the system will go up by 1 briefly, but go back to the previous amount right after)

**Comment by MartinSVK12** [comment]
Came to the conclusion that this can't really be fixed without changing how buildcraft pipes work.
