### ISSUE TITLE
crash on second page of Digital Terminal (1.1 for BTA)

### ISSUE THREAD

**Issue by MrMirajIzHere** [MartinSVK12/retrostorage#22]
every time i open second page of digital terminal game crashes
upd: all other pages work just fine (tested 3 and 4)

![Скриншот 16-03-2023 184629](https://user-images.githubusercontent.com/106516237/225564791-e744dbe9-710f-4a0b-bf3c-98f533a6819d.png)

**Comment by MartinSVK12** [comment]
Can you provide the full stacktrace?

**Comment by MartinSVK12** [comment]
stale and no response
