### ISSUE TITLE
Item exporter duplication/voiding bug

### ISSUE THREAD

**Issue by rythin-sr** [MartinSVK12/retrostorage#3]
Duplication:

https://user-images.githubusercontent.com/49848633/173829238-fc1f225a-9733-4909-840a-72e1eeb54dd8.mp4

Voiding:

https://user-images.githubusercontent.com/49848633/173829841-0912521a-6a69-4008-8625-f151784ca216.mp4

Reproduction steps:
Voiding:
-set up a system with a digital terminal and an exporter pointing to a chest
-put two stacks of 64 items into the system
-put in another, non-64 stack
-set the exporter to export the items you just put in
-the chest should only have one 64 stack and the non-64 stack, deleting the second 64 stack

Duplicating:
-put a 64 stack of an item into the system
-put multiple non-64 stacks into the system
-set the exporter to export the item you just put in
-every non-64 stack should have turned into a 64-stack in the chest, except the last one

**Comment by MartinSVK12** [comment]
Both fixed.
