### ISSUE TITLE
Digital Terminal duplication bug

### ISSUE THREAD

**Issue by rythin-sr** [MartinSVK12/retrostorage#4]
Reproduction steps:
-have a system with a terminal and a disc drive
-put in one stack of 64 items into the terminal
-put in 10 more of the same item, one by one
-you should now see 2 stacks of 64 among the single-stacks
-taking one 64-stack out will create another one, this will repeat for every single 1-stack except the last one

https://user-images.githubusercontent.com/49848633/173832982-ac8250e5-97f0-4ac4-be1a-39e5f687116b.mp4

**Comment by rythin-sr** [comment]
A similar effect can be achieved by putting one 64-stack into the terminal and then two or more 1-stacks. Taking out the 64-stack will duplicate one of the 1-stacks until it reaches 64 in a similar fashion as above.

**Comment by MartinSVK12** [comment]
Fixed.
