### ISSUE TITLE
Digital Terminal duplication bug #2

### ISSUE THREAD

**Issue by rythin-sr** [MartinSVK12/retrostorage#7]
Clicking an item on the terminal display with another item of the same type on the cursor will fill the stack on the cursor without taking out items from the system, provided that the amount in the system + the stack on the cursor <= 64.

https://user-images.githubusercontent.com/49848633/173835907-3b5ecac2-71f0-48e9-9dec-1a0c35010cd3.mp4

**Comment by MartinSVK12** [comment]
Fixed.
